### ISSUE TITLE
boost::core::string_view

### ISSUE THREAD

**Issue by Tradias** [klemens-morgenstern/boost.tcl#1]
I believe Boost projects should use `boost::core::basic_string_view` instead of `boost/utility/string_view.hpp`. Do you have any intel on that? I mean if not, then why was `boost::core::basic_string_view` even added?

**Comment by klemens-morgenstern** [comment]
I didn't even notice you this issue until now, sorry. From what I remember it was that utility didn't get regular updates by it's maintainer so a second one was created.
